version: '3.8'


services:
  shopdemodb:
    image: postgres:alpine3.16
    container_name: shopdemodb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ShopDemo
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_demo:/var/lib/postgresql/data
  
  #web app
  shopdemo.webapp:
    image: ${DOCKER_REGISTRY-}shopdemo-webapp:${PLATFORM:-linux}-${TAG:-latest}
    container_name: shopdemo.webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=shopdemodb;Port=5432;Database=ShopDemo;User Id=admin;Password=admin1234"
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: ShopDemo/Dockerfile
    depends_on:
      - shopdemodb

networks:
  default:
    name: shopdemo
    driver: bridge

volumes:
  postgres_data_demo:
    name: postgres_data_demo
